version: 0.2

phases:
  install:
    commands:
      - echo "Adding node_modules/.bin to PATH..."
      - export PATH="$PATH:$PWD/node_modules/.bin"
      - echo "Installing all npm dependencies..."
      - npm install
  
  pre_build:
    commands:
      - echo "Running code linting..."
      - npm run lint
      - echo "Getting Git commit hash..."
      - COMMIT_HASH=$(git rev-parse --short HEAD)
      - echo "REACT_APP_GIT_REVISION=$COMMIT_HASH" > .env.production.local
      - cat .env.production.local              

  build:
    commands:
      - echo "Running the build command..."
      - npm run build:css && react-scripts build

# 'artifacts' defines which files to upload to S3 from the build.
artifacts:
  files:
    - '**/*'
  base-directory: build