version: 0.2

phases:
  # The 'install' phase is for installing all necessary dependencies.
  install:
    commands:
      # We first add the local node_modules bin directory to the PATH.
      # This ensures that commands like 'react-scripts' can be found.
      - echo "Adding node_modules/.bin to PATH..."
      - export PATH="$PATH:$PWD/node_modules/.bin"
      
      # This command installs all packages listed in your package.json.
      # This is crucial to run before the build process starts.
      # Ensure that 'react-scripts' is listed as a devDependency in your package.json.
      - echo "Installing all npm dependencies..."
      - npm install
  
  # The 'pre_build' phase is for running pre-build tasks like linting and testing.
  # This is a great place to fail the build early if code quality standards aren't met.
  pre_build:
    commands:
      # Run linting to check for code style issues and potential errors.
      # The command `npm run lint` will now be executed here.
      # If linting fails, the build will stop here, preventing bad code from being deployed.
      - echo "Running code linting..."
      - npm run lint        

  # The 'build' phase is for compiling your code.
  build:
    commands:
      # We chain the CSS build and the main React build together.
      # The '&&' ensures that the React build will only run if the CSS build
      # completes successfully.
      - echo "Running the build command..."
      - npm run build:css && react-scripts build

      # This command will sync your build artifacts to S3.
      # Because it's in the 'build' phase and comes after the build command,
      # it will only be executed if the 'npm run build' command is successful.
      # This prevents the S3 bucket from being deleted on a build failure.
      - echo "Syncing React build artifacts to S3 bucket $S3_BUCKET_NAME..."
      - aws s3 sync ./build s3://$S3_BUCKET_NAME --delete

# 'artifacts' defines which files to upload to S3 from the build.
artifacts:
  files:
    - '**/*'
  base-directory: build
