version: 0.2

phases:
  # The 'install' phase is for installing all necessary dependencies.
  install:
    commands:
      # This command installs all packages listed in your package.json,
      # including axios and react-icons. It is crucial to run this
      # before the build process starts.
      - echo "Installing all npm dependencies..."
      - npm install
  
  # The 'build' phase is for compiling your code.
  build:
    commands:
      # We chain the CSS build and the main React build together.
      # The '&&' ensures that the React build will only run if the CSS build
      # completes successfully.
      - echo "Running the build command..."
      - npm run build:css && react-scripts build

      # This command will sync your build artifacts to S3.
      # Because it's in the 'build' phase and comes after the build command,
      # it will only be executed if the 'npm run build' command is successful.
      # This prevents the S3 bucket from being deleted on a build failure.
      - echo "Syncing React build artifacts to S3 bucket $S3_BUCKET_NAME..."
      - aws s3 sync ./build s3://$S3_BUCKET_NAME --delete

# 'artifacts' defines which files to upload to S3 from the build.
artifacts:
  files:
    - '**/*'
  base-directory: build
